parameters:
    p_saunders_example.repository.user_repository: PSaunders\Bundle\ExampleBundle\Repository\UserRepository

services:
    p_saunders_example.repository.user_repository:
        class: %p_saunders_example.repository.user_repository%